// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVOwJIeqw6437K64KsQjYgRr_WGimtjns',
    appId: '1:187152910840:web:19f88f58fc5641fa736e0d',
    messagingSenderId: '187152910840',
    projectId: 'chatapplication2-6e864',
    authDomain: 'chatapplication2-6e864.firebaseapp.com',
    storageBucket: 'chatapplication2-6e864.appspot.com',
    measurementId: 'G-4F7X8LXB0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJCTcnml62p00MuyI2m4P502GYToVaO1s',
    appId: '1:187152910840:android:628362af1ef7c7ce736e0d',
    messagingSenderId: '187152910840',
    projectId: 'chatapplication2-6e864',
    storageBucket: 'chatapplication2-6e864.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPgg1rIfOnmr1zaMXRRFHqWwe7Ep8xpFs',
    appId: '1:187152910840:ios:9b32c595c835525f736e0d',
    messagingSenderId: '187152910840',
    projectId: 'chatapplication2-6e864',
    storageBucket: 'chatapplication2-6e864.appspot.com',
    iosBundleId: 'com.example.flutterChatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPgg1rIfOnmr1zaMXRRFHqWwe7Ep8xpFs',
    appId: '1:187152910840:ios:3c45fc37393d4a73736e0d',
    messagingSenderId: '187152910840',
    projectId: 'chatapplication2-6e864',
    storageBucket: 'chatapplication2-6e864.appspot.com',
    iosBundleId: 'com.example.flutterChatApplication.RunnerTests',
  );
}
